[package]
name = "rustybin"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
rocket = "*"
rocket_codegen = "*"
redis = "*"
uuid = { version = "0.5.1", features = ["v4"] }
failure = "*"
failure_derive = "*"
time = "*"
url = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
